// Intentionally no include guard.

// Undefines all of our macros.

#undef MB_FILE
#undef MB_END_FILE
#undef MB_NAMESPACE
#undef MB_END_NAMESPACE
#undef MB_FUNC
#undef MB_CLASS
#undef MB_END_CLASS
#undef MB_ENUM
#undef MB_TYPEDEF
#undef MB_REGISTER_TYPE
#undef MB_REGISTER_TYPE_RETURNED
#undef MB_REGISTER_TYPE_PARAM
#undef MB_REGISTER_TYPE_PARSED
#undef MB_REGISTER_TYPE_BASE
#undef MB_REGISTER_TYPE_NONSTATIC_DATA_MEMBER
#undef MB_REGISTER_TYPE_STATIC_DATA_MEMBER
#undef MB_REGISTER_TYPE_TYPEDEF_TARGET
#undef MB_ALT_TYPE_SPELLING
#undef MB_ALT_TYPE_SPELLING_RETURNED
#undef MB_ALT_TYPE_SPELLING_PARAM
#undef MB_ALT_TYPE_SPELLING_PARSED
#undef MB_ALT_TYPE_SPELLING_BASE
#undef MB_ALT_TYPE_SPELLING_NONSTATIC_DATA_MEMBER
#undef MB_ALT_TYPE_SPELLING_STATIC_DATA_MEMBER
#undef MB_ALT_TYPE_SPELLING_TYPEDEF_TARGET
#undef MB_ALT_TYPE_SPELLING_TYPEDEF_NAME
