#include <input/MR/1.h>
#include <input/MR/2.h>
#include <input/MR/test_bases.h>
#include <input/MR/test_iostream.h>
#include <input/MR/test_nested_class_template_inst.h>
#include <input/MR/test_phmap.h>
#include <input/MR/test_simple_types.h>
#include <input/MR/test_std_containers.h>
#include <input/MR/test_std_expected.h>
#include <input/MR/test_std_filesystem.h>
#include <input/MR/test_std_function.h>
#include <input/MR/test_std_optional.h>
#include <input/MR/test_std_shared_ptr.h>
#include <input/MR/test_std_string.h>
#include <input/MR/test_std_string_view.h>
#include <input/MR/test_std_tuple_like.h>
#include <input/MR/test_std_unique_ptr.h>
#include <input/MR/test_typedefs_in_templates.h>
#include <input/MR/test_variant.h>
