name: Build LLVM

on:
  workflow_dispatch:
    inputs:
      llvm-version:
        required: true
        type: string

jobs:
  create-release:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Create release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create "llvm-${{ inputs.llvm-version }}" \
            --draft \
            --title "LLVM ${{ inputs.llvm-version }}"

  build-linux:
    needs:
      - create-release
    runs-on: ${{ matrix.runner }}
    container:
      image: almalinux:8
    strategy:
      fail-fast: false
      matrix:
        arch: [x64, arm64]
        include:
          - arch: x64
            runner: ubuntu-24.04
          - arch: arm64
            runner: ubuntu-24.04-arm

    steps:
      - name: Install tools
        run: |
          dnf install -y epel-release
          dnf install -y --enablerepo powertools \
            gcc-toolset-14 cmake ninja-build \
            $(: CI requirements ) \
            git \
            $(: LLVM build requirements ) \
            python3 xz

      - name: Checkout
        uses: actions/checkout@v6

      - name: Download LLVM
        run: |
          ci/download_llvm.sh "${{ inputs.llvm-version }}"

      - name: Build libclang
        run: |
          source /opt/rh/gcc-toolset-14/enable
          ci/build_llvm.sh

      - name: Create package
        run: |
          dnf install -y zip
          mv llvm-out llvm
          zip -r llvm-linux-$(uname -m).zip llvm/

      - name: Upload package
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # TODO: use a ready-made universal GitHub action
          dnf config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo
          dnf install -y gh
          # fix git permissions
          export HOME=${RUNNER_TEMP}
          git config --global --add safe.directory '*'
          # upload package
          gh release upload "llvm-${{ inputs.llvm-version }}" llvm-linux-$(uname -m).zip --clobber
